### ISSUE TITLE
Sharing a file / folder

### ISSUE THREAD

**Issue by gedw99** [kuking/seof#4]
Is this use case one you are considering ?

i want to share a folder with my friend and so would like them to get a key that allows them access to only that folder.

If the complete encrypted file system was synchronised the above use case allows teams to share access to parts of the whole.

**Comment by kuking** [comment]
Maybe that is a tool you can built on top of seof, but it is not something you can do with seof “as is” now.

Comes to mind encrypted dar files, age. Maybe those tools are more suited for your needs.
